# CI workflow для benadis-runner
# Запускается при push и pull request
name: CI

on:
  push:
    branches:
      - main
      - 'rf*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Install Wire CLI
        run: go install github.com/google/wire/cmd/wire@v0.6.0

      - name: Generate Wire
        run: make generate-wire

      - name: Verify Wire Generated
        run: |
          git diff --exit-code internal/di/wire_gen.go || {
            echo "::error::wire_gen.go не актуален. Запустите 'make generate-wire' и закоммитьте изменения."
            exit 1
          }

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out $(go list ./... | grep -v /smoketest)

      - name: Run smoke tests
        run: make test-smoke

      - name: Build
        run: make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m
