// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Kargones/apk-ci/internal/config"

	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp создаёт и инициализирует App через Wire DI.
// Принимает внешний Config (загруженный через config.MustLoad()).
//
// Wire генерирует реализацию этой функции в wire_gen.go.
// Функция здесь является "заглушкой" с wire.Build() вызовом.
//
// Пример использования:
//
//	cfg, err := config.MustLoad()
//	if err != nil {
//	    log.Fatal(err)
//	}
//	app, err := di.InitializeApp(cfg)
//	if err != nil {
//	    log.Fatal(err)
//	}
//	// Использование: app.Logger, app.OutputWriter, app.TraceID
//
// Циклические зависимости между провайдерами обнаруживаются на этапе
// компиляции при генерации wire_gen.go (AC4).
// Проверка nil Config выполняется в runtime в сгенерированном InitializeApp (AC3).
func InitializeApp(cfg *config.Config) (*App, error) {
	logger := ProvideLogger(cfg)
	writer := ProvideOutputWriter()
	string2 := ProvideTraceID()
	factory := ProvideFactory(cfg)
	alerter := ProvideAlerter(cfg, logger)
	collector := ProvideMetricsCollector(cfg, logger)
	tracerShutdown := ProvideTracerProvider(cfg, logger)
	app := &App{
		Config:           cfg,
		Logger:           logger,
		OutputWriter:     writer,
		TraceID:          string2,
		OneCFactory:      factory,
		Alerter:          alerter,
		MetricsCollector: collector,
		TracerShutdown:   tracerShutdown,
	}
	return app, nil
}

// wire.go:

// ProviderSet объединяет все провайдеры приложения.
// Используется в InitializeApp для построения графа зависимостей.
//
// При добавлении новых провайдеров:
// 1. Создать функцию провайдера в providers.go
// 2. Добавить её в ProviderSet
// 3. Перегенерировать: go generate ./internal/di/...
var ProviderSet = wire.NewSet(
	ProvideLogger,
	ProvideOutputWriter,
	ProvideTraceID,
	ProvideFactory,
	ProvideAlerter,
	ProvideMetricsCollector,
	ProvideTracerProvider,
	wire.Struct(new(App), "*"),
)
