```yaml
#1. Обновление тестовых баз.yaml
on:
  workflow_dispatch:
    inputs:
      restore_DB:
        description: 'Восстановить базу перед загрузкой конфигурации'
        required: true
        type: boolean
        default: false 
      service_mode_enable:
        description: 'Включить сервисный режим (отключать только для загрузки конфигузации без применения)'
        required: true
        type: boolean
        default: true 
      load_cfg:
        description: 'Загрузить конфигурацию из хранилища'
        required: true
        type: boolean
        default: true 
      DbName:
        description: 'Выберите базу для загрузки конфигурации (Test)'
        required: true
        default: '<Первая база из списка в options>'
        type: choice
        options:
        <Список баз из Config.ProjectConfig.Prod.<Имя прод базы>.related. Например:
        - V8_DEV_DSBEKETOV_APK_TOIR3
        - V8_TEST_KONTUR_APK_TOIR3 >
      update_conf:
        description: 'Применить конфигурацию после загрузки'
        required: true
        type: boolean
        default: true 
jobs:               
  db-update-test:
    runs-on: edt
    steps:
      - name: Восстановление базы данных (Test)
        id: br-dbrestore
        if: ${{ inputs.restore_DB == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "dbrestore"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}
          
      - name: Включение сервисного режима (Test)
        id: br-service-mode-enable
        if: ${{ inputs.service_mode_enable == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "service-mode-enable"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}
          
      - name: Загрузка конфигурации из хранилища (Test)
        id: br-store2db
        if: ${{ inputs.load_cfg == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "store2db"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}

      - name: Применение конфигурации (Test)
        id: br-dbupdate
        if: ${{ inputs.update_conf == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "dbupdate"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}

      - name: Отключение сервисного режима (Test)
        id: br-service-mode-disable
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "service-mode-disable"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}
```

```yaml
 #2. Обновление прод баз.yaml
on:
  workflow_dispatch:
    inputs:
      service_mode_enable:
        description: 'Включить сервисный режим (отключать только для загрузки конфигузации без применения)'
        required: true
        type: boolean
        default: true 
      load_cfg:
        description: 'Загрузить конфигурацию из хранилища'
        required: true
        type: boolean
        default: true 
      DbName:
        description: 'Выберите базу для загрузки конфигурации (Prod)'
        required: true
        default: '<Первая база из списка в options>'
        type: choice
        options:
        <Список баз из Config.ProjectConfig.Prod.<Имя прод базы> вида <Config.ProjectConfig.Prod.<Имя прод базы>.dbName (Config.ProjectConfig.Prod.<Имя прод базы>)> Например:
        - База ТОИР (V8_OPER_APK_TOIR3) >
      update_conf:
        description: 'Применить конфигурацию после загрузки'
        required: true
        type: boolean
        default: true 
jobs:               
  db-update-test:
    runs-on: edt
    steps:
      - name: Включение сервисного режима (Prod)
        id: br-service-mode-enable
        if: ${{ inputs.service_mode_enable == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "service-mode-enable"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}
          
      - name: Загрузка конфигурации из хранилища (Prod)
        id: br-store2db
        if: ${{ inputs.load_cfg == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "store2db"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}

      - name: Применение конфигурации (Prod)
        id: br-dbupdate
        if: ${{ inputs.update_conf == true }}
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "dbupdate"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}

      - name: Отключение сервисного режима (Prod)
        id: br-service-mode-disable
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ gitea.server_url }}
          repository: ${{ gitea.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "service-mode-disable"
          logLevel: "Debug"
          dbName: ${{ inputs.DbName }}
          actor: ${{ gitea.actor }}
```
Шаблон расположенный ниже не изменяется
```yaml
#авто. Конвертация и перенос в хранилище.yaml
name: Конвертация и перенос в хранилище
run-name: ${{ gitea.event_name }} - ${{ gitea.workflow }} - ${{ gitea.actor }}
on:
  release:
    types: [published]
jobs:
  convert-and-store:
    runs-on: edt
    steps:
      - name: Конвертация
        id: br-convert
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ github.server_url }}
          repository: ${{ github.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "convert"
          logLevel: "Debug"
          actor: ${{ gitea.actor }}
      - name: Перенос в хранилище
        id: br-convert
        uses: https://${{ secrets.TOKEN_FULL }}:@regdv.apkholding.ru/gitops-tools/benadis-runner@latest
        with:
          giteaURL: ${{ github.server_url }}
          repository: ${{ github.repository }}
          accessToken: ${{ secrets.TOKEN_FULL }}
          command: "git2store"
          logLevel: "Debug"
          actor: ${{ gitea.actor }}
```
