@startuml
title SQ Commands Activity Diagram

start

:Получение команды
====
команда (sq-scan-branch, sq-scan-pr, sq-project-update, sq-repo-sync, sq-repo-clear, sq-report-pr, sq-report-branch, sq-report-project)
параметры команды
----
результат выполнения команды;

if (Команда?) then (sq-scan-branch)
    :Получить данные о ветке из Gitea API
    ====
    owner
    repo
    branch
    ----
    данные о ветке (первый коммит при создании ветки);

    if (Ветка != main?) then (Да)
        :Получить первый коммит ветки
        ====
        owner
        repo
        branch
        ----
        первый коммит ветки;
    else (Нет)
    endif

    :Получить данные о проекте из SonarQube API
    ====
    owner
    repo
    branch
    ----
    данные о проекте (существование проекта);

    if (Проект существует?) then (Нет)
        :Создать новый проект в SonarQube
        ====
        owner
        repo
        branch
        ----
        ключ проекта;
    else (Да)
    endif

    if (commit_hash передан?) then (Нет)
        if (Ветка == main?) then (Да)
            :Сканировать последний коммит ветки
            ====
            owner
            repo
            branch
            ----
            результат сканирования;
        else (Нет)
            :Проверить наличие сканирования базового коммита
            ====
            owner
            repo
            branch
            commit_hash (базовый коммит)
            ----
            наличие сканирования;

            if (Сканирование есть?) then (Нет)
                :Сканировать базовый коммит
                ====
                owner
                repo
                branch
                commit_hash (базовый коммит)
                ----
                результат сканирования;

                :Сканировать текущий коммит
                ====
                owner
                repo
                branch
                commit_hash (текущий коммит)
                ----
                результат сканирования;
            else (Да)
                :Сканировать текущий коммит
                ====
                owner
                repo
                branch
                commit_hash (текущий коммит)
                ----
                результат сканирования;
            endif
        endif
    else (Да)
        :Сканировать состояние репозитория на указанный коммит
        ====
        owner
        repo
        branch
        commit_hash
        ----
        результат сканирования;
    endif

elseif (Команда?) then (sq-scan-pr)
    :Получить данные PR из Gitea API
    ====
    owner
    repo
    pr
    ----
    данные PR (имя ветки источника, первый коммит, последний коммит);

    :Получить имя ветки источника
    ====
    данные PR
    ----
    имя ветки источника;

    :Вызвать sq-scan-branch с пустым commit_hash
    ====
    owner
    repo
    ветка источника
    пустой commit_hash
    ----
    результат сканирования;

elseif (Команда?) then (sq-project-update)
    :Обновить описание проекта из README.md
    ====
    owner
    repo
    ----
    обновленное описание проекта;

    :Синхронизировать список администраторов с группами owners и dev
    ====
    owner
    repo
    branch
    ----
    обновленный список администраторов;

elseif (Команда?) then (sq-repo-sync)
    :Получить список веток из Gitea API
    ====
    owner
    repo
    ----
    список веток;

    :Получить список проектов из SonarQube API
    ====
    owner
    repo
    ----
    список проектов;

    fork
        repeat
            :Для каждой ветки
            ====
            ветка
            ----
            обработанная ветка;

            if (Проект существует?) then (Да)
                :Вызвать sq-project-update
                ====
                owner
                repo
                branch
                ----
                результат обновления проекта;
            else (Нет)
                :Вызвать sq-scan-branch с пустым commit_hash
                ====
                owner
                repo
                branch
                пустой commit_hash
                ----
                результат сканирования;
            endif
        repeat while (Есть еще ветки?)
    fork again
        :Вызвать sq-repo-clear
        ====
        owner
        repo
        force
        ----
        результат очистки;
        fork end

    elseif (Команда?) then (sq-repo-clear)
        :Получить sq_wait_for_delete из app.yaml
        ====
        ----
        sq_wait_for_delete (время в секундах);

        :Получить список веток из Gitea API
        ====
        owner
        repo
        ----
        список веток;

            :Получить список проектов из SonarQube API
            ====
            owner
            repo
            ----
            список проектов;

            repeat
                :Для каждого проекта
                ====
                проект
                ----
                обработанный проект;

                :Проверить соответствие ветке
                ====
                проект
                список веток
                ----
                соответствие ветке;

                if (Проект соответствует ветке?) then (Нет)
                    if (force == true?) then (Да)
                        :Удалить проект
                        ====
                        имя проекта
                        ----
                        результат удаления;
                    else (Нет)
                        :Проверить время последнего сканирования
                        ====
                        проект
                        ----
                        время последнего сканирования;

                        if (Прошло > sq_wait_for_delete?) then (Да)
                            :Удалить проект
                            ====
                            имя проекта
                            ----
                            результат удаления;
                        else (Нет)
                            :Вывести сообщение о несоответствии
                            ====
                            проект
                            ----
                            сообщение о несоответствии;
                        endif
                    endif
                else (Да)
                endif
            repeat while (Есть еще проекты?)

    elseif (Команда?) then (sq-report-pr)
        :Получить данные PR из Gitea API
        ====
        owner
        repo
        pr
        ----
        данные PR (имя ветки источника, первый коммит, последний коммит);

        :Получить имя ветки источника
        ====
        данные PR
        ----
        имя ветки источника;

        :Получить первый коммит ветки
        ====
        данные PR
        ----
        первый коммит ветки;

        :Получить последний коммит PR
        ====
        данные PR
        ----
        последний коммит PR;

        :Вызвать sq-report-branch
        ====
        owner
        repo
        ветка источника
        первый коммит
        последний коммит
        ----
        отчет по ветке;

        :Сформировать отчет по PR
        ====
        отчет по ветке
        ----
        отчет по PR;

        :Разместить отчет в задаче репозитория
        ====
        owner
        repo
        pr
        отчет по PR
        ----
        результат размещения отчета;

    elseif (Команда?) then (sq-report-branch)
        :Получить ошибки между коммитами из SonarQube API
        ====
        owner
        repo
        branch
        first_commit_hash
        last_commit_hash
        ----
        ошибки между коммитами;

        :Вернуть отчет в формате JSON
        ====
        ошибки между коммитами
        ----
        отчет в формате JSON;

    elseif (Команда?) then (sq-report-project)
        :Получить данные о ветках из Gitea API
        ====
        owner
        repo
        ----
        данные о ветках;

        repeat
            :Для каждой ветки
            ====
            ветка
            ----
            обработанная ветка;

            if (Ветка == main?) then (Да)
                :Получить второй коммит ветки
                ====
                ветка
                ----
                второй коммит ветки;

                :Получить последний коммит ветки
                ====
                ветка
                ----
                последний коммит ветки;
            else (Нет)
                :Получить первый коммит ветки
                ====
                ветка
                ----
                первый коммит ветки;

                :Получить последний коммит ветки
                ====
                ветка
                ----
                последний коммит ветки;
            endif

            :Вызвать sq-report-branch
            ====
            owner
            repo
            branch
            первый/второй коммит
            последний коммит
            ----
            отчет по ветке;
        repeat while (Есть еще ветки?)
    endif

    stop
    @enduml