@startuml Benadis.UI
skin rose
skinparam maxMessageSize 70

start
group Получение настроек
    :Получение организаций доступных пользователю;
    :Выбор организации;
    :Определение групп пользователя;
    end group
    if (Принадлежит группе TEST) then (Да)
        :Показываем закладку Тестировщик;
    endif
    if (Принадлежит группе DEV) then (Да)
        :Показываем закладку Разработчик;
    endif
    if (Принадлежит группе RM) then (Да)
        :Показываем закладку Релиз менеджер;
    endif


end
@enduml