@startuml Фоновое сканирование
skin rose
skinparam maxMessageSize 70

start
:Генерируем файл скрипта;
:Сохраняем его во временный файл;
:Запускаем на исполнение с помощью утилиты для скрытия консоли;
:Продолжаем работу;
:Получаем оповещение о завершении;



end



@enduml