@startuml Git2Store
skin rose
skinparam maxMessageSize 70

start
:Получение настроек;
:Получение данных из репозитория;
:Создание временной базы;
:Создание расширений;
:Сортируем каталоги так чтобы Main был первым;
note right:Иначе при загрузке расширения будет ошибка
group Выгрузка
    repeat :Выбираем очередной каталог;
    :Загружаем файлы в базу;
    if (Это Main?) then (да)
        :Грузить в основную конфигурацию;
    else (нет)
        :Грузить в расширение;
    endif
    :Применить изменения;
    if (Это Main?) then (да)
        :Выгрузить cf из конфигурации;
    else (нет)
        :Выгрузить cfe из расширения;
    endif
    :Захватить все объекты в хранилище;
    if (Это Main?) then (да)
        :Объединить cf с хранилищем;
    else (нет)
        :Объединить cfe с хранилищем;
    endif
    :Поместить версию в хранилище со снятием блокировки;
    repeat while (Есть еще каталоги)
    :Отключить базы от хранилища;
    end group
end
note right: Нужно обрабатывать ошибки возникающие в процессе

@enduml
' echo off
' Set StorePath=C:\Tools\StoreProd
' Set StoreUser=Администратор
' Set StorePass=Администратор

' cd C:\Tools\StoreDev\StoreToGit
' call git add . && git commit -m "Изменение" && git push
' cd C:\Tools\GitToCf\StoreToGit
' call git pull


' "C:\Program Files\1cv8\8.3.22.1923\bin\1cv8.exe" DESIGNER /f C:\Tools\GitToCf /LoadConfigFromFiles C:\Tools\GitToCf\StoreToGit\cfg /UpdateDBCfg  /out c:\tmp\1_1_log.out /DisableStartupDialogs /DisableStartupMessages /DisableUnrecoverableErrorMessage
' "C:\Program Files\1cv8\8.3.22.1923\bin\1cv8.exe" DESIGNER /f C:\Tools\GitToCf /DumpCfg C:\Tools\GitToCf\dump.cf  /out c:\tmp\1_2_log.out /DisableStartupDialogs /DisableStartupMessages /DisableUnrecoverableErrorMessage
' "C:\Program Files\1cv8\8.3.22.1923\bin\1cv8.exe" DESIGNER /f C:\Tools\StoreConv /ConfigurationRepositoryF %StorePath% /ConfigurationRepositoryN %StoreUser% /ConfigurationRepositoryP %StorePass% /ConfigurationRepositoryLock /out c:\tmp\2_1_log.out /DisableStartupDialogs /DisableStartupMessages /DisableUnrecoverableErrorMessage
' "C:\Program Files\1cv8\8.3.22.1923\bin\1cv8.exe" DESIGNER /f C:\Tools\StoreConv  /ConfigurationRepositoryF %StorePath% /ConfigurationRepositoryN %StoreUser% /ConfigurationRepositoryP %StorePass% /MergeCfg C:\Tools\GitToCf\dump.cf -Settings "C:\Tools\GitToCf\MergeSettingsКонфигурация.xml" -force /out c:\tmp\2_2_log.out /DisableStartupDialogs /DisableStartupMessages /DisableUnrecoverableErrorMessage /UpdateDBCfg
' "C:\Program Files\1cv8\8.3.22.1923\bin\1cv8.exe" DESIGNER /f C:\Tools\StoreConv  /ConfigurationRepositoryF %StorePath% /ConfigurationRepositoryN %StoreUser% /ConfigurationRepositoryP %StorePass% /ConfigurationRepositoryCommit -comment "Автоматически добавленная версия" -keepLocked -force /out c:\tmp\2_3_log.out /DisableStartupDialogs /DisableStartupMessages /DisableUnrecoverableErrorMessage
