@startuml Временная диаграмма
skin rose
hide unlinked
skinparam maxMessageSize 100
autonumber 1.1
entity HelpDesk as hd
boundary SonarQube as sq
control "Среда разработки" as r1
collections "Хранилище\nразработки" as s1
queue DEV_CONF as dc
queue tXXXXXX as det
queue bXXXX as deb
queue DEV_EDT as de
queue DEV as d
collections "Хранилище\nтестирования" as s2
database "База для\nтестирования" as dt
collections "Хранилище\nрабочей базы" as s3
database "Рабочая база" as dw

group Подготовка задач для разработки
  hd -> hd : Работа с заявками
  hd -> hd : Согласование задачи
end

==Разработка\n**Начало==
autonumber inc A
group Разработчик в EDT
  hd -> r1 : Получение задач для разработки
  de -> det : Создание ветки для задачи
  activate det
  note right det: Создание ветки для задачи всегда производится из актуальной версии.\nЕсли ветка задачи становится неактуальной (висит несколько релизов)\nпри возвращении к разработке нужно актуализировать ее произведя\nMerge __в эту ветку__ ветки DEV_EDT
  r1 -> r1 : Разработка в рамках задачи
  r1 -> det : Коммит в репозиторий
  r1 -> sq : Сканирование изменений
  sq -> r1 : Получение отчета
  r1 -> r1 : Исправление замечаний
  r1 -> det : Коммит в репозиторий
end

==Разработка\n**Конец==
autonumber inc A
==Релизный комитет\n**Начало==
hd -> hd : Проверка состояния задач
hd -> hd : Утверждение задач в релиз
==Релизный комитет\n**Конец==
autonumber inc A
==Подготовка релиза\n**Начало==
group Релиз менеджер
  hd -> hd : Получение списка задач в релиз
  det -> de : Слияние с веткой DEV_EDT
  destroy det
  note left: При успешном слиянии ветка удаляется
  de -> de : Создание релиза [fXX.XX.XX.xx]
  note left de: Создание кандидата в релиз **f**
  note right d: Номера релизов XX.XX.XX.xx\nдолжны совпадать
  de -> d : Конвертация релиз-кандидата edt -> xml
  d -> d : Создание релиза [rcXX.XX.XX.xx]
end
==Подготовка релиза\n**Конец==
autonumber inc A
==Тестирование\n**Начало==
group Тестировщик
  d -> s2 : Обновление тестового хранилища
  s2 -> dt : Обновление тестовой базы
  alt Найдены ошибки
    dt -> dt : Тестирование
    d <- dt : Создание задачи на исправление ошибок
  end
end

group Разработчик в EDT
  de -> deb : Создание ветки DEV_EDT_tBFxxxx
  activate deb
  note right deb: xxxx - соответвтвует номеру задачи\nна исправление ошибки созданному\nтестировщиком
  deb -> r1 : Получение актуальной версии
  r1 -> r1 : Исправление ошибки
  r1 -> deb : Коммит в репозиторий
  r1 -> sq : Сканирование изменений
  sq -> r1 : Получение отчета
  r1 -> r1 : Исправление замечаний
  r1 -> deb : Коммит в репозиторий
end

group Релиз менеджер
  deb -> de : Слияние с веткой DEV_EDT
  destroy deb
  note left: При успешном слиянии ветка удаляется
  de -> de: revert отмененных задач
  de -> de : Создание релиза [fXX.XX.XX.xx]
  note left de: Создание кандидата в релиз **f**
  note right d: Номера релизов XX.XX.XX.xx\nдолжны совпадать
  de -> d : Конвертация релиз-кандидата edt -> xml
  d -> d : Создание релиза [rcXX.XX.XX.xx]
end

group Тестировщик
  d -> s2 : Обновление тестового хранилища
  s2 -> dt : Обновление тестовой базы
  alt Ошибок не найдено
    dt -> dt : Тестирование
  end
end
group Релиз менеджер
  note right d: ==**Релиз для рабочей базы** \n==\nПереименовываем последний релиз\nутвержденный тестировщиками
  d -> d : Создание релиза [rXX.XX.XX.xx]
end
==Тестирование\n**Конец==

autonumber inc A
==Обновление рабочей базы\n**Начало==
group Ответственный за обновление
  d -> s3 : Обновление хранилища рабочей базы
  s3 -> dw : Обновление рабочей базы
  dw -> dw : Проверка работы
  dw -> d : Подтверждение корректности релиза
end
==Обновление рабочей базы\n**Конец==

autonumber inc A
==Актуализация среды разработки\n**Начало==
group Релиз менеджер
  de -> de : Переименовываем последний **f** (пункт 5.15) в **fr**
end
note right de:После актуализации ветки она не\nменяется до следующего релиза.\nДля разработки используются ветки\n**tXXXXXX**
==Актуализация среды разработки\n**Конец==
==↑Возвращаемся в начало схемы↑==
legend
  **Права на запись в ветку DEV_EDT есть __только__ у Релиз менеджера, такая схема в рамках разработки на EDT позволит существенно сократить время на выпуск релизов и исправление ошибок.
end legend
@enduml
