@startuml Временная диаграмма
skin rose
hide unlinked
skinparam maxMessageSize 100
autonumber 1.1
entity HelpDesk as hd
boundary SonarQube as sq
control "Среда разработки" as r1
collections "Хранилище\nразработки" as s1
queue DEV_CONF as dc
queue DEV_EDT_xxxxxx as det
queue DEV_EDT as de
queue DEV_EDT_XML as dex
queue DEV as d
queue TEST as t
collections "Хранилище\nтестирования" as s2
database "База для\nтестирования" as dt
queue PROD as p

collections "Хранилище\nрабочей базы" as s3
database "Рабочая база" as dw
' *********************
group Подготовка задач для разработки
hd -> hd : Работа с заявками
hd -> hd : Согласование задачи
end

autonumber inc A
==Разработка\n**Начало==
group Разработчик в конфигураторе
hd -> r1 : Получение задач для разработки
r1 -> r1 : Разработка в рамках задачи
r1 -> s1 : Помещение задачи в хранилище
s1 -> dc : Коммит в репозиторий
end
note right: 
autonumber inc A
group Разработчик в EDT
hd -> r1 : Получение задач для разработки
de -> det : Создание ветки для задачи
activate det
r1 -> r1 : Разработка в рамках задачи
r1 -> det : Коммит в репозиторий
r1 -> sq : Сканирование изменений
sq -> r1 : Получение отчета
r1 -> r1 : Исправление замечаний
r1 -> det : Коммит в репозиторий
end

==Разработка\n**Конец==
autonumber inc A
==Релизный комитет\n**Начало==
hd -> hd : Проверка состояния задач
hd -> hd : Утверждение задач в релиз
==Релизный комитет\n**Конец==
autonumber inc A
==Подготовка релиза\n**Начало==
group Релиз менеджер
det -> de : Слияние с веткой DEV_EDT
destroy det
note left: При успешном слиянии ветка удаляется
de -> dex : Конвертация edt -> xml
dc -> d : Слияние внесенных изменений
dex -> d : Слияние внесенных изменений
d -> d : Создание релиза
end
==Подготовка релиза\n**Конец==
autonumber inc A
==Тестирование\n**Начало==
group Тестировщик
d -> t : Получение релиза
t -> s2 : Обновление тестового хранилища
s2 -> dt : Обновление тестовой базы
alt Найдены ошибки
dt -> dt : Тестирование
d <- dt : Создание задачи на исправление ошибок
end
end

group Релиз менеджер
d -> dc : Обновление репозитория
dc -> s1 : Обновление хранилища
d -> dex: Обновление репозитория
dex -> de : Конвертация xml -> edt
end
group Разработчик в конфигураторе
s1 -> r1 : Получение актуальной версии
r1 -> r1 : Исправление ошибки
r1 -> s1 : Помещение задачи в хранилище
s1 -> dc : Коммит в репозиторий
end
group Разработчик в EDT
de -> r1 : Получение актуальной версии
r1 -> r1 : Исправление ошибки
r1 -> de : Коммит в репозиторий
de -> dex : Конвертация edt -> xml
end
group Релиз менеджер
dc -> d : Слияние внесенных изменений
dex -> d : Слияние внесенных изменений
d -> d : Создание релиза
end

group Тестировщик
d -> t : Получение релиза
t -> s2 : Обновление тестового хранилища
s2 -> dt : Обновление тестовой базы
alt Ошибок не найдено
dt -> dt : Тестирование
d -> p : Перенос релиза в репозиторий PROD
end
end
==Тестирование\n**Конец==
autonumber inc A
==Обновление рабочей базы\n**Начало==
group Ответственный за обновление
p -> s3 : Обновление хранилища рабочей базы
s3 -> dw : Обновление рабочей базы
dw -> dw : Проверка работы
dw -> d : Подтверждение корректности релиза
end
==Обновление рабочей базы\n**Конец==
autonumber inc A
==Актуализация среды разработки\n**Начало==
group Релиз менеджер
d -> dc : Обновление репозитория
dc -> s1 : Обновление хранилища
d -> dex: Обновление репозитория
dex -> de : Конвертация xml -> edt
end
group Разработчик в конфигураторе
s1 -> r1 : Получение актуальной версии
end
group Разработчик в EDT
de -> r1 : Получение актуальной версии
end
==Актуализация среды разработки\n**Конец==
==↑Возвращаемся в начало схемы↑==
@enduml
