@startuml Описание процесса
skin rose
skinparam maxMessageSize 70
title Процесс обновления хранилища из git (v2).

start

:Загрузка конфигурации среды исполнения;
:Загрузка конфигурации задачи;
if (Полное обновление) then (Да)
    :Установка параметров критического обновления
    ====
    Критическое обновление доступно = **Ложь**
    ----
    База загрузки/выгрузки исправлений актуальна = **Ложь**
    ----
    База обновления хранилища актуальна = **Ложь**]
    fork
        fork
            :Загрузка репозитория;

        fork again
            :Создание временной базы для выгрузки cf и cfe;
            repeat: Есть не созданные расширения
            :Получение данных расширения из настроек;
            :Добавление расширения;
            repeat while
        end fork
        :Загрузка конфигурации из файлов;
        :Применение изменений конфигурации;

        repeat: Есть не загруженные расширения
        :Загрузка расширения из файлов;
        :Применение изменений расширения;
        package #Gray "Задача второго этапа" {
            :Проверка применимости расширения;
            if (Проверка прошла успешно) then (Да)
            else (Нет)
                if (Расширение критическое) then (Да)
                    :Падаем с ошибкой;
                    end
                else (Нет)
                endif
            endif
        }
        repeat while

        :Выгружаем конфигурацию в файл main.cf;

        repeat: Есть не выгруженные расширения
        :Выгружаем расширение в файл ИмяРасширения.cfe;
        repeat while

    fork again
        note: Можно брать базу из левой ветки, но так красивее
        :Создание временной базы для подключения к хранилищу;
        repeat: Есть не созданные расширения
        :Получение данных расширения из настроек;
        :Добавление расширения;
        repeat while
        :Подключаем конфигурацию к хранилищу;
        :Применяем изменения конфигурации;
        :Захватываем объекты конфигурации в хранилище;
        repeat: Есть не подключенные расширения
        :Подключаем расширение к хранилищу;
        :Применяем изменения расширения;
        :Захватываем объекты расширения в хранилище;
        repeat while

    end fork
    fork
        :Объединяем объекты конфигурации с файлом main.cf;
        :Применяем изменения объектов конфигурации;

        repeat: Есть не объединенные расширения
        :Объединяем объекты расширения с файлом ИмяРасширения.cfe;
        :Применяем изменения объектов расширения;
        repeat while

        if (Были ошибки?) then (Нет)
        else (Да)
            :Отменяем захват объектов конфигурации;
            :Отключаем конфигурацию от хранилища;
            repeat: Есть захваченные объекты расширения
            :Отменяем захват объектов расширения;
            :Отключаем расширение от хранилища;
            repeat while
            :Падаем с ошибкой;
            end
        endif
        :Помещаем версию конфигурации в хранилище
        ----
        при помещении в хранилище отменяем захват объектов;
        :Отключаем конфигурацию от хранилища;
        repeat: Есть не помещенные версии расширений
        :Помещаем версию расширения в хранилище
        ----
        при помещении в хранилище отменяем захват объектов;
        :Отключаем расширение от хранилища;
        repeat while
    fork again
        if (Поддерживается критическое обновление) then (Да)
            partition Обновление базы для загрузки расширения "Исправления"\nиз файлов и выгрузки в cfe {
                :Загружаем конфигурацию из файла main.cf;
                :Применяем изменения объектов конфигурации;

                repeat: Есть не загруженные расширения
                :Загружаем расширения из файлов ИмяРасширения.cfe;
                :Применяем изменения объектов расширения;
                repeat while
            }
            :Установка параметров критического обновления
            ====
            База загрузки/выгрузки исправлений актуальна = **Истина**]

        else (Нет)
            :Не стартуем этот поток;
            end

        endif
    end fork
    if (Поддерживается критическое обновление) then (Нет)

    else (Да)
        partition Обновление базы для обновления расширения "Исправления"\nв хранилище {
            :Получаем из хранилища последнюю версию;
            :Применяем изменения объектов конфигурации;
            repeat: Есть не обновленные расширения
            :Получаем из хранилища последнюю версию расширения;
            :Применяем изменения объектов расширения;
            repeat while
        }
        :Установка параметров критического обновления
        ====
        База обновления хранилища актуальна = **Истина**]

        if (База загрузки/выгрузки исправлений актуальна = **Истина**\nИ\nБаза обновления хранилища актуальна = **Истина**) then (Да)
            :Установка параметров критического обновления
            ====
            Критическое обновление доступно = **Истина**]

        endif
    endif

else (Исправление ошибки в проде)
    note right: Только для тяжелых баз
    if (Критическое обновление доступно) then (Истина)

        fork
            :Загрузка из git каталога расширения "Исправления";
            :Загрузка расширения "Изменения" из файлов
            ----
            Загрузка производится в
            "База загрузки/выгрузки исправлений";
            :Применение изменений расширения "Исправления";
            package #Gray "Задача второго этапа" {
                :Проверка применимости расширения;
                if (Проверка прошла успешно) then (Да)
                else (Нет)
                    if (Расширение критическое) then (Да)
                        :Падаем с ошибкой;
                        end
                    else (Нет)
                    endif
                endif
            }
            :Выгружаем расширение в файл Исправления.cfe;
        fork again
            :Захват объектов расширения\n"Исправления" в хранилище
            ----
            Захват производится в "База обновления хранилища";
        end fork
        :Объединяем объекты расширения с файлом Исправления.cfe
        ----
        Объединение производится в "База обновления хранилища";

        :Применяем изменения объектов расширения "Исправления";
        :Помещаем версию расширения "Исправления" в хранилище
        ----
        Отмена захват объектов расширения "Исправления"
        производится при помещении версии в хранилище;
    else (Ложь)
        :Падаем с ошибкой
        ----
        Служебные базы не актуальны;
        end
    endif
endif
:Радуемся;

legend
    **Для быстрого прохождения критического обновления требуется:**
    ----
    #Постоянно хранящаяся база для загрузки из xml и выгрузки в cfe расширения "Исправления". База должна иметь актуальную основную конфигурацию и расширения.
    Без использования этой базы для выгрузки расширения сначала прийдется загрузить из исходников и применить изменения основной конфигурации.
    #Постоянно хранящаяся база подключенная к хранилищу для загрузки расширения из cfe.
    Без использования этой базы перед объединением расширения нужно будет актуализировать
    ----
    ** При данной схеме сокращение времени работы процесса для тяжелых конфигураций почти вдвое.
    ** Для гарантии атомарности обновления хранилища целесообразно копировать каталог локально
    и заменять исходный каталог только в случае успешного завершения процесса.
    ** Большая часть обработок ошибок опущена для большей наглядности схемы.
end legend
end
@enduml
