@startuml branch_loop v3.9.18

skin rose

'control Паралельный as Паралельный
collections Prod as Prod
collections Dev as Dev
collections Dev_conf as Dev_conf
collections xxxxxx_conf as xxxxxx_conf
collections Dev_edt as Dev_edt
collections xxxxxx_edt as xxxxxx_edt
collections Test as Test
'control процесс as процесс

header Цикл разработки с использованием сервера git
footer Предварительная версия
Title Последовательность работы с ветками репозитория
Prod -> Dev : Актуализация\nветки
note left: Обновление N
group Разработка в конфигураторе
Dev -> Dev_conf : Актуализация\nветки
Dev_conf -> xxxxxx_conf : Создание\nветки задачи
note left: Имя ветки состоит из номера\nзадачи и постфикса _conf
xxxxxx_conf -> xxxxxx_conf : Разработка\nв рамках\nзадачи
xxxxxx_conf -> Dev_conf : Слияние после\nзавершения
note right: Ветка\n**удаляется**
Dev_conf -> Dev : Слияние\nрелиза
note right: Ветка\n**сохраняется**
end
group Разработка в EDT
Dev -> Dev_edt : Актуализация\nветки
Dev_edt -> xxxxxx_edt : Создание\nветки задачи
note left: Имя ветки состоит из номера\nзадачи и постфикса _edt
xxxxxx_edt -> xxxxxx_edt : Разработка\nв рамках\nзадачи
xxxxxx_edt -> Dev_edt : Слияние после\nзавершения
note right: Ветка\n**удаляется**
Dev_edt -> Dev : Слияние\nрелиза
note right: Ветка\n**сохраняется**
end
group Подготовка релиза для рабочей базы
Dev -> Dev : Создание релиза
Dev -> Test : Релиз для тестирования
Test -> Test : Тестирование\nрелиза
Test -> Dev : Выявленные ошибки
Dev -> Dev : Исправление\nошибок
note left : Возможно повторение\nцикла разработки
Dev -> Test : Релиз для тестирования
Test -> Test : Тестирование\nрелиза
Test -> Prod : Релиз рабочей базы
end
Prod -> Dev : Актуализация\nветки
note left: Обновление N+1
legend
"Разработка в конфигураторе" и "Разработка в EDT" ведутся ** параллельно**
Ветки Prod, Dev, Dev_conf, Dev_edt и Test - постоянные ветки.
Ветки вида xxxxxx_conf и xxxxxx_edt - используются для разработки в рамках конкретной задачи.
Для больших задач при разработке на EDT возможно создание веток вида xxxxxx_<LoginName>.
end legend
@enduml