@startuml Создание задачи
skin rose
skinparam maxMessageSize 70

start
:Получение настроек]
:Выбор номера задачи<
:Выбор репозитория<
:Поиск данных по задаче в HelpDesk}
:Поиск ветки вида _хххххх в репозитории]
if (Ветка есть?) then (нет)
    :Создаем ветку _хххххх]
    note left: **1
else (да)
    if (Обновить существующую?) then (нет)
        :Создаем ветку _хххххх]
        note left: **1
    else (да)
        :Заменяем содержимое ветки актуальным релизом]
    endif
endif
:Создание проекта _хххххх в SonarQube]
:Создание скрипта для запуска сканирования]
note right: Желательно оптимизировать сканирование\n по измененным объектам


end




legend
    **1 Создание веток _хххххх всегда производится из последнего актуального релиза
end legend

@enduml