@startuml Схема разработки

skin rose
skinparam actorStyle awesome
title Схема разработки
actor "Релиз\nменеджер" as rm
actor "Тестировщик" as tm

package Конфигуратор {
    actor "Разработчик" as R1
    actor "Разработчик" as R2
}
package EDT {
    actor "Разработчик" as R3
    actor "Разработчик" as R4
}
collections "Хранилище\nразработки" as s1
collections "Хранилище\nтестирования" as s2
collections "Хранилище\nрабочей\nбазы" as s3
database "База для\nтестирования" as dbT
database "Рабочая база" as dbP
component GIT {
    component DEV
    component DEV_EDT
    component DEV_EDT_XML
    component DEV_CONF
    component TEST
    component PROD
}
s1 <-up- R1 : Помещение\nв хранилище
s1 -up-> R1 : Получение\nактуального\nсостояния
s1 <-up- R2 : Помещение\nв хранилище
s1 -up-> R2 : Получение\nактуального\nсостояния
DEV_EDT <-up- R3
DEV_EDT <-up- R4
DEV_EDT -up-> R3
DEV_EDT -up-> R4

s1 <-- DEV_CONF : Актуализация\nхранилища [1]
s1 --> DEV_CONF : Актуализация\nрепозитория

DEV <-up- DEV_CONF : Слияние
DEV -up-> DEV_CONF : Получение\nактуальной\nверсии
DEV <-up- DEV_EDT_XML : Слияние
DEV -up-> DEV_EDT_XML : Получение\nактуальной\nверсии
DEV_EDT_XML <-up- DEV_EDT : Конвертация\nв xml
DEV_EDT_XML -up-> DEV_EDT : Конвертация\nиз xml\n(Получение\nактуальной\nверсии)
DEV <.right. rm : Управление слиянием
DEV <.right. rm : Выпуск релизов
TEST <-up- DEV : Релиз для тестирования
s2 <-left- TEST : Обновление\nтестового\nхранилища
PROD <-up- TEST : Выпуск релиза
DEV <.. tm : Создание задач\nпо выявленным ошибкам
dbT <.up. tm : Тестирование\nрелиза
dbT <-- s2 : Обновление\nтестового\nконтура
TEST <.up. tm : Утверждение\nрелиза для PROD
s3 <-up- PROD : Обновление хранилища\nрабочей базы
dbP <-up- s3 : Тестирование\nрелиза

legend
[1] - Актуализация хранилища производится после обновления рабочей базы

end legend

@enduml