@startuml Проверка PR на конфликты
skin rose
skinparam maxMessageSize 70
title Проверка PR на конфликты
start

:Получаю список активных PR\nотсортированных по дате создания]
if (Есть активные PR) then (да)
else (нет)
    stop
endif

:Создаю ветку test_merge из main]
: --Сортирую PR по ID--]
' note right: Получаем порядок\nочередности PR

repeat :Получаю очередной PR]
:Создаю тестовый PR  к ветке\ntest_merge на основе текущего PR]
:Провожу слияние]
if (Слияние прошло успешно?) then (да)
    : --Удаляю тестовый PR--]
    note: Не требуется, удаляется\n при удалении ветки
else (нет)
    :Добавляю PR в список конфликтов]
endif
repeat while (Есть необработанные PR?) is (да)

:Удаляю ветку test_merge]

repeat :Получаю очередной PR из списка конфликтов]
:Закрываю соответствующий ему PR]
:Удаляю тестовый PR]
repeat while (Есть необработанные конфликтые PR?) is (да)

stop
@enduml