@startuml Схема удаленной разработки

skin rose
skinparam actorStyle awesome
title Схема удаленной разработки

package "EDT стандартный вариант" {
    package "Рабочее место" {
        actor "Разработчик" as R1
        collections "EDT" as e1
        collections "1C AgentMode" as a1
    }
    package "Наша инфраструктура" {
        collections "Сервер 1С" as s1
        database "База для\nразработки" as dbd1
    }
}
' note:

R1 -down-> e1 : Ввод кода
e1 -down-> a1 : Управление конфигурацией
a1 -down-> s1 : Управление базой
s1 -down-> dbd1 : Управление базой
' package "EDT через git" {
'     actor "Разработчик" as R2
' }
legend
**Затраты траффика на типовые операции**
(данные приведены для ERP ДМПЗ)
    Подключение к удаленной базе: получено - **24 МБ**, отправлено - **200 КБ**
    Получение списка изменений базы: получено - **3 МБ**, отправлено - **100 КБ**
    Применение изменений в коде: получено - **13 МБ**, отправлено - **1.2 МБ**
    Запуск тонкого клиента: получено - **160 КБ**, отправлено - **80 КБ**

end legend

@enduml